# -*- coding: utf-8 -*-
"""housing price Predictive Modeling Using Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVwh37704xzZtX_zIFCZ18Wz2X0Yfgkr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,roc_curve,r2_score,mean_squared_error

df=pd.read_csv("/content/Housing.csv")

df.head()

df['price_category'] = (df['price'] > df['price'].median()).astype(int)
x=df["area"]
y = df['price_category']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=52)

lr=LinearRegression()
lr.fit(x_train.to_frame(),y_train)
y_pred=lr.predict(x_test.to_frame())
r2_score(y_test,y_pred)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
df['price_category'] = (df['price'] > df['price'].median()).astype(int)
x = df[['area']]
y = df['price_category']
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=52
)
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
c = confusion_matrix(y_test, y_pred)

print(c)

plt.plot(df['price'],df['area'])

plt.figure(figsize=(10, 6))
plt.scatter(x_test, y_test, color='blue', label='Actual Price Category (0 or 1)', alpha=0.6)
plt.plot(x_test, y_pred, color='red', label=f'Linear Regression Fit (R2 = {r2_score(y_test, y_pred):.2f})')
plt.title('Linear Regression: Area vs. Price Category with R2 Score')
plt.xlabel('Area')
plt.ylabel('Price Category (0=Low, 1=High)')
plt.legend()
plt.grid(True)
plt.show()

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
accuracy_score(y_test,y_pred)

plt.figure(figsize=(15,8))
plt.scatter(x_test,y_test,color="red")
plt.plot(x_test,y_pred,color="blue")
plt.xlabel("area")
plt.ylabel("price")
plt.show()

rf=RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
r2_score(y_test,y_pred)

plt.figure(figsize=(10,7))
plt.scatter(x_test,y_test,color="red")
plt.plot(x_test,y_pred,color="blue")
plt.grid()
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score

logistic_model = LogisticRegression(random_state=52)
logistic_model.fit(x_train, y_train)
y_pred_proba_lr = logistic_model.predict_proba(x_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba_lr)
auc = roc_auc_score(y_test, y_pred_proba_lr)
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='blue', label=f'ROC Curve (AUC = {auc:.2f})')
plt.plot([0, 1], [0, 1], color='red', linestyle='--', label='Random Classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Logistic Regression')
plt.legend()
plt.grid(True)
plt.show()